services:
  app:
    image: ruby
    command: sh -c "bundle && ruby server.rb" 
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 3000:3000
  postgres:
    image: postgres
    command: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
volumes:
  rubygems:
  pgdata: