-- Cria a tabela TESTS
CREATE TABLE TESTS (
  ID SERIAL PRIMARY KEY,
  PATIENT_REGISTRATION_NUMBER VARCHAR(14) NOT NULL,
  PATIENT_NAME VARCHAR(200) NOT NULL,
  PATIENT_EMAIL VARCHAR(100) NOT NULL,
  PATIENT_BIRTH_DATE DATE NOT NULL,
  PATIENT_ADDRESS VARCHAR(200) NOT NULL,
  PATIENT_CITY VARCHAR(64) NOT NULL,
  PATIENT_STATE VARCHAR(30) NOT NULL,
  DOCTOR_CRM VARCHAR(10) NOT NULL,
  DOCTOR_CRM_STATE VARCHAR(2) NOT NULL,
  DOCTOR_NAME VARCHAR(200) NOT NULL,
  DOCTOR_EMAIL VARCHAR(100) NOT NULL,
  TEST_TOKEN VARCHAR(6) NOT NULL,
  TEST_DATE DATE NOT NULL,
  TEST_TYPE VARCHAR(30) NOT NULL,
  TEST_LIMITS VARCHAR(10) NOT NULL,
  TEST_RESULT VARCHAR(5) NOT NULL
);
